project:
  type: website

website:
  title: "James Henry"
  favicon: images/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coaching.qmd
        text: Coaching
      - href: stats.qmd
        text: Stats
      - href: playing.qmd
        text: Playing
    right:
      - icon: "file-earmark-person"
        href: assets/James-Henry-Resume.docx
        aria-label: "Click to download my resume"
      - icon: images/favicon.ico
        href: wwww.google.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



